/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get redacted runtime config */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.EnvResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product inventory */
        get: {
            parameters: {
                query?: {
                    /** @description max items per page (≤ 200) */
                    limit?: number;
                    /** @description page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description RFC 8288 next/prev links */
                        Link?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        /** Create a product */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description product to create */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product inventory */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description product SKU */
                    sku: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{sku}/productionEvent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record a production event */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description product SKU */
                    sku: string;
                };
                cookie?: never;
            };
            /** @description production event */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["CreateProductionEventRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductionEventResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reservations */
        get: {
            parameters: {
                query?: {
                    /** @description filter by SKU */
                    sku?: string;
                    /** @description filter by state */
                    state?: "Open" | "Closed";
                    /** @description max items per page (≤ 200) */
                    limit?: number;
                    /** @description page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description RFC 8288 next/prev links */
                        Link?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        /** Create a reservation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description reservation request */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["ReservationRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation/{ID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a reservation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description reservation ID */
                    ID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description new user */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_user.CreateUserRequestDto"];
                };
            };
            responses: {
                /** @description created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a bearer token
         * @description Requires HTTP Basic credentials (RFC 6749 §2.3.1 OAuth2 client_credentials flow).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.TokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Catalog is the optional enrichment from the upstream catalog
         *     service (DSN-018). Omitted when the catalog client is disabled
         *     or when the upstream is unreachable — the inventory response
         *     still succeeds in that case.
         */
        CatalogInfo: {
            category?: string;
            description?: string;
        };
        CreateProductRequest: {
            name?: string;
            sku?: string;
            upc?: string;
        };
        CreateProductionEventRequest: {
            created?: string;
            id?: number;
            quantity?: number;
            requestID?: string;
        };
        FieldProblem: {
            detail?: string;
            field?: string;
        };
        Problem: {
            detail?: string;
            errors?: components["schemas"]["FieldProblem"][];
            instance?: string;
            status?: number;
            title?: string;
            type?: string;
        };
        ProductResponse: {
            available?: number;
            catalog?: components["schemas"]["CatalogInfo"];
            name?: string;
            sku?: string;
            upc?: string;
        };
        ProductionEventResponse: Record<string, never>;
        ReservationRequestDto: {
            quantity?: number;
            requestId?: string;
            requester?: string;
            sku?: string;
        };
        ReservationResponse: {
            created?: string;
            id?: number;
            requestId?: string;
            requestedQuantity?: number;
            requester?: string;
            reservedQuantity?: number;
            sku?: string;
            state?: components["schemas"]["ReserveState"];
        };
        /** @enum {string} */
        ReserveState: "Open" | "Closed" | "";
        "api.EnvResponse": {
            appName?: components["schemas"]["config.StringConfig"];
            appVersion?: components["schemas"]["config.StringConfig"];
            buildTime?: components["schemas"]["config.StringConfig"];
            catalog?: components["schemas"]["config.CatalogConfig"];
            config?: components["schemas"]["config.ConfigSource"];
            db?: components["schemas"]["config.DbConfig"];
            docs?: components["schemas"]["config.DocsConfig"];
            idempotency?: components["schemas"]["config.IdempotencyConfig"];
            kafka?: components["schemas"]["config.KafkaConfig"];
            log?: components["schemas"]["config.LogConfig"];
            port?: components["schemas"]["config.StringConfig"];
            profile?: components["schemas"]["config.StringConfig"];
            rabbitmq?: components["schemas"]["config.QueueConfig"];
            rateLimit?: components["schemas"]["config.RateLimitConfig"];
            redis?: components["schemas"]["config.RedisConfig"];
            revision?: components["schemas"]["config.StringConfig"];
            sha1Version?: components["schemas"]["config.StringConfig"];
        };
        "api.TokenResponse": {
            access_token?: string;
            expires_in?: number;
            token_type?: string;
        };
        "config.BoolConfig": {
            default?: boolean;
            description?: string;
            value?: boolean;
        };
        "config.CatalogConfig": {
            baseUrl?: components["schemas"]["config.StringConfig"];
            description?: string;
            maxAttempts?: components["schemas"]["config.IntConfig"];
            perAttemptMs?: components["schemas"]["config.IntConfig"];
            timeoutMs?: components["schemas"]["config.IntConfig"];
        };
        "config.ConfigSource": {
            description?: string;
            print?: components["schemas"]["config.BoolConfig"];
            source?: components["schemas"]["config.StringConfig"];
            spring?: components["schemas"]["config.SpringConfig"];
        };
        "config.DbConfig": {
            clean?: components["schemas"]["config.BoolConfig"];
            description?: string;
            host?: components["schemas"]["config.StringConfig"];
            logLevel?: components["schemas"]["config.StringConfig"];
            migrate?: components["schemas"]["config.BoolConfig"];
            migrationFolder?: components["schemas"]["config.StringConfig"];
            name?: components["schemas"]["config.StringConfig"];
            pass?: components["schemas"]["config.StringConfig"];
            pool?: components["schemas"]["config.DbPoolConfig"];
            port?: components["schemas"]["config.StringConfig"];
            user?: components["schemas"]["config.StringConfig"];
        };
        "config.DbPoolConfig": {
            description?: string;
            healthCheckPeriod?: components["schemas"]["config.IntConfig"];
            maxConnIdle?: components["schemas"]["config.IntConfig"];
            maxConnLife?: components["schemas"]["config.IntConfig"];
            maxPoolSize?: components["schemas"]["config.IntConfig"];
            minPoolSize?: components["schemas"]["config.IntConfig"];
        };
        "config.DocsConfig": {
            description?: string;
            enabled?: components["schemas"]["config.BoolConfig"];
        };
        "config.FloatConfig": {
            default?: number;
            description?: string;
            value?: number;
        };
        "config.IdempotencyConfig": {
            description?: string;
            ttlMinutes?: components["schemas"]["config.IntConfig"];
        };
        "config.IntConfig": {
            default?: number;
            description?: string;
            value?: number;
        };
        "config.InventoryQueueConfig": {
            description?: string;
            exchange?: components["schemas"]["config.StringConfig"];
        };
        "config.KafkaConfig": {
            brokers?: components["schemas"]["config.StringConfig"];
            commandsTopic?: components["schemas"]["config.StringConfig"];
            consumerGroup?: components["schemas"]["config.StringConfig"];
            description?: string;
            dltTopic?: components["schemas"]["config.StringConfig"];
            eventsTopic?: components["schemas"]["config.StringConfig"];
        };
        "config.LogConfig": {
            description?: string;
            level?: components["schemas"]["config.StringConfig"];
            structured?: components["schemas"]["config.BoolConfig"];
        };
        "config.ProductQueueConfig": {
            description?: string;
            dlt?: components["schemas"]["config.ProductQueueDltConfig"];
            queue?: components["schemas"]["config.StringConfig"];
        };
        "config.ProductQueueDltConfig": {
            description?: string;
            exchange?: components["schemas"]["config.StringConfig"];
        };
        "config.QueueConfig": {
            description?: string;
            host?: components["schemas"]["config.StringConfig"];
            inventory?: components["schemas"]["config.InventoryQueueConfig"];
            pass?: components["schemas"]["config.StringConfig"];
            port?: components["schemas"]["config.StringConfig"];
            product?: components["schemas"]["config.ProductQueueConfig"];
            reservation?: components["schemas"]["config.ReservationQueueConfig"];
            user?: components["schemas"]["config.StringConfig"];
        };
        "config.RateLimitConfig": {
            authBurst?: components["schemas"]["config.IntConfig"];
            authRatePerSecond?: components["schemas"]["config.FloatConfig"];
            description?: string;
        };
        "config.RedisConfig": {
            cacheTtlMinutes?: components["schemas"]["config.IntConfig"];
            description?: string;
            url?: components["schemas"]["config.StringConfig"];
            userCacheTtlSeconds?: components["schemas"]["config.IntConfig"];
        };
        "config.ReservationQueueConfig": {
            description?: string;
            exchange?: components["schemas"]["config.StringConfig"];
        };
        "config.SpringConfig": {
            branch?: components["schemas"]["config.StringConfig"];
            description?: string;
            pass?: components["schemas"]["config.StringConfig"];
            url?: components["schemas"]["config.StringConfig"];
            user?: components["schemas"]["config.StringConfig"];
        };
        "config.StringConfig": {
            default?: string;
            description?: string;
            value?: string;
        };
        "internal_user.CreateUserRequestDto": {
            isAdmin?: boolean;
            password?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
