// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for GithubComSksmithGoMicroExampleCoreInventoryReserveState.
const (
	GithubComSksmithGoMicroExampleCoreInventoryReserveStateClosed GithubComSksmithGoMicroExampleCoreInventoryReserveState = "Closed"
	GithubComSksmithGoMicroExampleCoreInventoryReserveStateNone   GithubComSksmithGoMicroExampleCoreInventoryReserveState = ""
	GithubComSksmithGoMicroExampleCoreInventoryReserveStateOpen   GithubComSksmithGoMicroExampleCoreInventoryReserveState = "Open"
)

// Valid indicates whether the value is a known member of the GithubComSksmithGoMicroExampleCoreInventoryReserveState enum.
func (e GithubComSksmithGoMicroExampleCoreInventoryReserveState) Valid() bool {
	switch e {
	case GithubComSksmithGoMicroExampleCoreInventoryReserveStateClosed:
		return true
	case GithubComSksmithGoMicroExampleCoreInventoryReserveStateNone:
		return true
	case GithubComSksmithGoMicroExampleCoreInventoryReserveStateOpen:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1ReservationParamsState.
const (
	GetApiV1ReservationParamsStateClosed GetApiV1ReservationParamsState = "Closed"
	GetApiV1ReservationParamsStateOpen   GetApiV1ReservationParamsState = "Open"
)

// Valid indicates whether the value is a known member of the GetApiV1ReservationParamsState enum.
func (e GetApiV1ReservationParamsState) Valid() bool {
	switch e {
	case GetApiV1ReservationParamsStateClosed:
		return true
	case GetApiV1ReservationParamsStateOpen:
		return true
	default:
		return false
	}
}

// ApiCreateProductRequest defines model for api.CreateProductRequest.
type ApiCreateProductRequest struct {
	Name *string `json:"name,omitempty"`
	Sku  *string `json:"sku,omitempty"`
	Upc  *string `json:"upc,omitempty"`
}

// ApiCreateProductionEventRequest defines model for api.CreateProductionEventRequest.
type ApiCreateProductionEventRequest struct {
	Created   *string `json:"created,omitempty"`
	Id        *int    `json:"id,omitempty"`
	Quantity  *int    `json:"quantity,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
}

// ApiCreateUserRequestDto defines model for api.CreateUserRequestDto.
type ApiCreateUserRequestDto struct {
	IsAdmin  *bool   `json:"isAdmin,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ApiEnvResponse defines model for api.EnvResponse.
type ApiEnvResponse struct {
	AppName     *ConfigStringConfig `json:"appName,omitempty"`
	AppVersion  *ConfigStringConfig `json:"appVersion,omitempty"`
	BuildTime   *ConfigStringConfig `json:"buildTime,omitempty"`
	Config      *ConfigConfigSource `json:"config,omitempty"`
	Db          *ConfigDbConfig     `json:"db,omitempty"`
	Docs        *ConfigDocsConfig   `json:"docs,omitempty"`
	Log         *ConfigLogConfig    `json:"log,omitempty"`
	Port        *ConfigStringConfig `json:"port,omitempty"`
	Profile     *ConfigStringConfig `json:"profile,omitempty"`
	Rabbitmq    *ConfigQueueConfig  `json:"rabbitmq,omitempty"`
	Revision    *ConfigStringConfig `json:"revision,omitempty"`
	Sha1Version *ConfigStringConfig `json:"sha1Version,omitempty"`
}

// ApiFieldProblem defines model for api.FieldProblem.
type ApiFieldProblem struct {
	Detail *string `json:"detail,omitempty"`
	Field  *string `json:"field,omitempty"`
}

// ApiProblem defines model for api.Problem.
type ApiProblem struct {
	Detail   *string            `json:"detail,omitempty"`
	Errors   *[]ApiFieldProblem `json:"errors,omitempty"`
	Instance *string            `json:"instance,omitempty"`
	Status   *int               `json:"status,omitempty"`
	Title    *string            `json:"title,omitempty"`
	Type     *string            `json:"type,omitempty"`
}

// ApiProductResponse defines model for api.ProductResponse.
type ApiProductResponse struct {
	Available *int    `json:"available,omitempty"`
	Name      *string `json:"name,omitempty"`
	Sku       *string `json:"sku,omitempty"`
	Upc       *string `json:"upc,omitempty"`
}

// ApiProductionEventResponse defines model for api.ProductionEventResponse.
type ApiProductionEventResponse = map[string]interface{}

// ApiReservationRequest defines model for api.ReservationRequest.
type ApiReservationRequest struct {
	Quantity  *int    `json:"quantity,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Requester *string `json:"requester,omitempty"`
	Sku       *string `json:"sku,omitempty"`
}

// ApiReservationResponse defines model for api.ReservationResponse.
type ApiReservationResponse struct {
	Created           *string                                                  `json:"created,omitempty"`
	Id                *int                                                     `json:"id,omitempty"`
	RequestId         *string                                                  `json:"requestId,omitempty"`
	RequestedQuantity *int                                                     `json:"requestedQuantity,omitempty"`
	Requester         *string                                                  `json:"requester,omitempty"`
	ReservedQuantity  *int                                                     `json:"reservedQuantity,omitempty"`
	Sku               *string                                                  `json:"sku,omitempty"`
	State             *GithubComSksmithGoMicroExampleCoreInventoryReserveState `json:"state,omitempty"`
}

// ApiTokenResponse defines model for api.TokenResponse.
type ApiTokenResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int    `json:"expires_in,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// ConfigBoolConfig defines model for config.BoolConfig.
type ConfigBoolConfig struct {
	Default     *bool   `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Value       *bool   `json:"value,omitempty"`
}

// ConfigConfigSource defines model for config.ConfigSource.
type ConfigConfigSource struct {
	Description *string             `json:"description,omitempty"`
	Print       *ConfigBoolConfig   `json:"print,omitempty"`
	Source      *ConfigStringConfig `json:"source,omitempty"`
	Spring      *ConfigSpringConfig `json:"spring,omitempty"`
}

// ConfigDbConfig defines model for config.DbConfig.
type ConfigDbConfig struct {
	Clean           *ConfigBoolConfig   `json:"clean,omitempty"`
	Description     *string             `json:"description,omitempty"`
	Host            *ConfigStringConfig `json:"host,omitempty"`
	LogLevel        *ConfigStringConfig `json:"logLevel,omitempty"`
	Migrate         *ConfigBoolConfig   `json:"migrate,omitempty"`
	MigrationFolder *ConfigStringConfig `json:"migrationFolder,omitempty"`
	Name            *ConfigStringConfig `json:"name,omitempty"`
	Pass            *ConfigStringConfig `json:"pass,omitempty"`
	Pool            *ConfigDbPoolConfig `json:"pool,omitempty"`
	Port            *ConfigStringConfig `json:"port,omitempty"`
	User            *ConfigStringConfig `json:"user,omitempty"`
}

// ConfigDbPoolConfig defines model for config.DbPoolConfig.
type ConfigDbPoolConfig struct {
	Description       *string          `json:"description,omitempty"`
	HealthCheckPeriod *ConfigIntConfig `json:"healthCheckPeriod,omitempty"`
	MaxConnIdle       *ConfigIntConfig `json:"maxConnIdle,omitempty"`
	MaxConnLife       *ConfigIntConfig `json:"maxConnLife,omitempty"`
	MaxPoolSize       *ConfigIntConfig `json:"maxPoolSize,omitempty"`
	MinPoolSize       *ConfigIntConfig `json:"minPoolSize,omitempty"`
}

// ConfigDocsConfig defines model for config.DocsConfig.
type ConfigDocsConfig struct {
	Description *string           `json:"description,omitempty"`
	Enabled     *ConfigBoolConfig `json:"enabled,omitempty"`
}

// ConfigIntConfig defines model for config.IntConfig.
type ConfigIntConfig struct {
	Default     *int    `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Value       *int    `json:"value,omitempty"`
}

// ConfigInventoryQueueConfig defines model for config.InventoryQueueConfig.
type ConfigInventoryQueueConfig struct {
	Description *string             `json:"description,omitempty"`
	Exchange    *ConfigStringConfig `json:"exchange,omitempty"`
}

// ConfigLogConfig defines model for config.LogConfig.
type ConfigLogConfig struct {
	Description *string             `json:"description,omitempty"`
	Level       *ConfigStringConfig `json:"level,omitempty"`
	Structured  *ConfigBoolConfig   `json:"structured,omitempty"`
}

// ConfigProductQueueConfig defines model for config.ProductQueueConfig.
type ConfigProductQueueConfig struct {
	Description *string                      `json:"description,omitempty"`
	Dlt         *ConfigProductQueueDltConfig `json:"dlt,omitempty"`
	Queue       *ConfigStringConfig          `json:"queue,omitempty"`
}

// ConfigProductQueueDltConfig defines model for config.ProductQueueDltConfig.
type ConfigProductQueueDltConfig struct {
	Description *string             `json:"description,omitempty"`
	Exchange    *ConfigStringConfig `json:"exchange,omitempty"`
}

// ConfigQueueConfig defines model for config.QueueConfig.
type ConfigQueueConfig struct {
	Description *string                       `json:"description,omitempty"`
	Host        *ConfigStringConfig           `json:"host,omitempty"`
	Inventory   *ConfigInventoryQueueConfig   `json:"inventory,omitempty"`
	Pass        *ConfigStringConfig           `json:"pass,omitempty"`
	Port        *ConfigStringConfig           `json:"port,omitempty"`
	Product     *ConfigProductQueueConfig     `json:"product,omitempty"`
	Reservation *ConfigReservationQueueConfig `json:"reservation,omitempty"`
	User        *ConfigStringConfig           `json:"user,omitempty"`
}

// ConfigReservationQueueConfig defines model for config.ReservationQueueConfig.
type ConfigReservationQueueConfig struct {
	Description *string             `json:"description,omitempty"`
	Exchange    *ConfigStringConfig `json:"exchange,omitempty"`
}

// ConfigSpringConfig defines model for config.SpringConfig.
type ConfigSpringConfig struct {
	Branch      *ConfigStringConfig `json:"branch,omitempty"`
	Description *string             `json:"description,omitempty"`
	Pass        *ConfigStringConfig `json:"pass,omitempty"`
	Url         *ConfigStringConfig `json:"url,omitempty"`
	User        *ConfigStringConfig `json:"user,omitempty"`
}

// ConfigStringConfig defines model for config.StringConfig.
type ConfigStringConfig struct {
	Default     *string `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Value       *string `json:"value,omitempty"`
}

// GithubComSksmithGoMicroExampleCoreInventoryReserveState defines model for github_com_sksmith_go-micro-example_core_inventory.ReserveState.
type GithubComSksmithGoMicroExampleCoreInventoryReserveState string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetApiV1InventoryParams defines parameters for GetApiV1Inventory.
type GetApiV1InventoryParams struct {
	// Limit max items per page (≤ 200)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset page offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PutApiV1InventoryJSONBody defines parameters for PutApiV1Inventory.
type PutApiV1InventoryJSONBody struct {
	union json.RawMessage
}

// PutApiV1InventoryJSONBody0 defines parameters for PutApiV1Inventory.
type PutApiV1InventoryJSONBody0 = map[string]interface{}

// PutApiV1InventorySkuProductionEventJSONBody defines parameters for PutApiV1InventorySkuProductionEvent.
type PutApiV1InventorySkuProductionEventJSONBody struct {
	union json.RawMessage
}

// PutApiV1InventorySkuProductionEventJSONBody0 defines parameters for PutApiV1InventorySkuProductionEvent.
type PutApiV1InventorySkuProductionEventJSONBody0 = map[string]interface{}

// GetApiV1ReservationParams defines parameters for GetApiV1Reservation.
type GetApiV1ReservationParams struct {
	// Sku filter by SKU
	Sku *string `form:"sku,omitempty" json:"sku,omitempty"`

	// State filter by state
	State *GetApiV1ReservationParamsState `form:"state,omitempty" json:"state,omitempty"`

	// Limit max items per page (≤ 200)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset page offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetApiV1ReservationParamsState defines parameters for GetApiV1Reservation.
type GetApiV1ReservationParamsState string

// PostApiV1ReservationJSONBody defines parameters for PostApiV1Reservation.
type PostApiV1ReservationJSONBody struct {
	union json.RawMessage
}

// PostApiV1ReservationJSONBody0 defines parameters for PostApiV1Reservation.
type PostApiV1ReservationJSONBody0 = map[string]interface{}

// PostApiV1UserJSONBody defines parameters for PostApiV1User.
type PostApiV1UserJSONBody struct {
	union json.RawMessage
}

// PostApiV1UserJSONBody0 defines parameters for PostApiV1User.
type PostApiV1UserJSONBody0 = map[string]interface{}

// PutApiV1InventoryJSONRequestBody defines body for PutApiV1Inventory for application/json ContentType.
type PutApiV1InventoryJSONRequestBody PutApiV1InventoryJSONBody

// PutApiV1InventorySkuProductionEventJSONRequestBody defines body for PutApiV1InventorySkuProductionEvent for application/json ContentType.
type PutApiV1InventorySkuProductionEventJSONRequestBody PutApiV1InventorySkuProductionEventJSONBody

// PostApiV1ReservationJSONRequestBody defines body for PostApiV1Reservation for application/json ContentType.
type PostApiV1ReservationJSONRequestBody PostApiV1ReservationJSONBody

// PostApiV1UserJSONRequestBody defines body for PostApiV1User for application/json ContentType.
type PostApiV1UserJSONRequestBody PostApiV1UserJSONBody

// AsPutApiV1InventoryJSONBody0 returns the union data inside the PutApiV1InventoryJSONBody as a PutApiV1InventoryJSONBody0
func (t PutApiV1InventoryJSONBody) AsPutApiV1InventoryJSONBody0() (PutApiV1InventoryJSONBody0, error) {
	var body PutApiV1InventoryJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPutApiV1InventoryJSONBody0 overwrites any union data inside the PutApiV1InventoryJSONBody as the provided PutApiV1InventoryJSONBody0
func (t *PutApiV1InventoryJSONBody) FromPutApiV1InventoryJSONBody0(v PutApiV1InventoryJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePutApiV1InventoryJSONBody0 performs a merge with any union data inside the PutApiV1InventoryJSONBody, using the provided PutApiV1InventoryJSONBody0
func (t *PutApiV1InventoryJSONBody) MergePutApiV1InventoryJSONBody0(v PutApiV1InventoryJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApiCreateProductRequest returns the union data inside the PutApiV1InventoryJSONBody as a ApiCreateProductRequest
func (t PutApiV1InventoryJSONBody) AsApiCreateProductRequest() (ApiCreateProductRequest, error) {
	var body ApiCreateProductRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCreateProductRequest overwrites any union data inside the PutApiV1InventoryJSONBody as the provided ApiCreateProductRequest
func (t *PutApiV1InventoryJSONBody) FromApiCreateProductRequest(v ApiCreateProductRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiCreateProductRequest performs a merge with any union data inside the PutApiV1InventoryJSONBody, using the provided ApiCreateProductRequest
func (t *PutApiV1InventoryJSONBody) MergeApiCreateProductRequest(v ApiCreateProductRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PutApiV1InventoryJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PutApiV1InventoryJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPutApiV1InventorySkuProductionEventJSONBody0 returns the union data inside the PutApiV1InventorySkuProductionEventJSONBody as a PutApiV1InventorySkuProductionEventJSONBody0
func (t PutApiV1InventorySkuProductionEventJSONBody) AsPutApiV1InventorySkuProductionEventJSONBody0() (PutApiV1InventorySkuProductionEventJSONBody0, error) {
	var body PutApiV1InventorySkuProductionEventJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPutApiV1InventorySkuProductionEventJSONBody0 overwrites any union data inside the PutApiV1InventorySkuProductionEventJSONBody as the provided PutApiV1InventorySkuProductionEventJSONBody0
func (t *PutApiV1InventorySkuProductionEventJSONBody) FromPutApiV1InventorySkuProductionEventJSONBody0(v PutApiV1InventorySkuProductionEventJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePutApiV1InventorySkuProductionEventJSONBody0 performs a merge with any union data inside the PutApiV1InventorySkuProductionEventJSONBody, using the provided PutApiV1InventorySkuProductionEventJSONBody0
func (t *PutApiV1InventorySkuProductionEventJSONBody) MergePutApiV1InventorySkuProductionEventJSONBody0(v PutApiV1InventorySkuProductionEventJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApiCreateProductionEventRequest returns the union data inside the PutApiV1InventorySkuProductionEventJSONBody as a ApiCreateProductionEventRequest
func (t PutApiV1InventorySkuProductionEventJSONBody) AsApiCreateProductionEventRequest() (ApiCreateProductionEventRequest, error) {
	var body ApiCreateProductionEventRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCreateProductionEventRequest overwrites any union data inside the PutApiV1InventorySkuProductionEventJSONBody as the provided ApiCreateProductionEventRequest
func (t *PutApiV1InventorySkuProductionEventJSONBody) FromApiCreateProductionEventRequest(v ApiCreateProductionEventRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiCreateProductionEventRequest performs a merge with any union data inside the PutApiV1InventorySkuProductionEventJSONBody, using the provided ApiCreateProductionEventRequest
func (t *PutApiV1InventorySkuProductionEventJSONBody) MergeApiCreateProductionEventRequest(v ApiCreateProductionEventRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PutApiV1InventorySkuProductionEventJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PutApiV1InventorySkuProductionEventJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1ReservationJSONBody0 returns the union data inside the PostApiV1ReservationJSONBody as a PostApiV1ReservationJSONBody0
func (t PostApiV1ReservationJSONBody) AsPostApiV1ReservationJSONBody0() (PostApiV1ReservationJSONBody0, error) {
	var body PostApiV1ReservationJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1ReservationJSONBody0 overwrites any union data inside the PostApiV1ReservationJSONBody as the provided PostApiV1ReservationJSONBody0
func (t *PostApiV1ReservationJSONBody) FromPostApiV1ReservationJSONBody0(v PostApiV1ReservationJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1ReservationJSONBody0 performs a merge with any union data inside the PostApiV1ReservationJSONBody, using the provided PostApiV1ReservationJSONBody0
func (t *PostApiV1ReservationJSONBody) MergePostApiV1ReservationJSONBody0(v PostApiV1ReservationJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApiReservationRequest returns the union data inside the PostApiV1ReservationJSONBody as a ApiReservationRequest
func (t PostApiV1ReservationJSONBody) AsApiReservationRequest() (ApiReservationRequest, error) {
	var body ApiReservationRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiReservationRequest overwrites any union data inside the PostApiV1ReservationJSONBody as the provided ApiReservationRequest
func (t *PostApiV1ReservationJSONBody) FromApiReservationRequest(v ApiReservationRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiReservationRequest performs a merge with any union data inside the PostApiV1ReservationJSONBody, using the provided ApiReservationRequest
func (t *PostApiV1ReservationJSONBody) MergeApiReservationRequest(v ApiReservationRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1ReservationJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1ReservationJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1UserJSONBody0 returns the union data inside the PostApiV1UserJSONBody as a PostApiV1UserJSONBody0
func (t PostApiV1UserJSONBody) AsPostApiV1UserJSONBody0() (PostApiV1UserJSONBody0, error) {
	var body PostApiV1UserJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1UserJSONBody0 overwrites any union data inside the PostApiV1UserJSONBody as the provided PostApiV1UserJSONBody0
func (t *PostApiV1UserJSONBody) FromPostApiV1UserJSONBody0(v PostApiV1UserJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1UserJSONBody0 performs a merge with any union data inside the PostApiV1UserJSONBody, using the provided PostApiV1UserJSONBody0
func (t *PostApiV1UserJSONBody) MergePostApiV1UserJSONBody0(v PostApiV1UserJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApiCreateUserRequestDto returns the union data inside the PostApiV1UserJSONBody as a ApiCreateUserRequestDto
func (t PostApiV1UserJSONBody) AsApiCreateUserRequestDto() (ApiCreateUserRequestDto, error) {
	var body ApiCreateUserRequestDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCreateUserRequestDto overwrites any union data inside the PostApiV1UserJSONBody as the provided ApiCreateUserRequestDto
func (t *PostApiV1UserJSONBody) FromApiCreateUserRequestDto(v ApiCreateUserRequestDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiCreateUserRequestDto performs a merge with any union data inside the PostApiV1UserJSONBody, using the provided ApiCreateUserRequestDto
func (t *PostApiV1UserJSONBody) MergeApiCreateUserRequestDto(v ApiCreateUserRequestDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1UserJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1UserJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiV1AdminEnv request
	GetApiV1AdminEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Inventory request
	GetApiV1Inventory(ctx context.Context, params *GetApiV1InventoryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1InventoryWithBody request with any body
	PutApiV1InventoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiV1Inventory(ctx context.Context, body PutApiV1InventoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1InventorySku request
	GetApiV1InventorySku(ctx context.Context, sku string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1InventorySkuProductionEventWithBody request with any body
	PutApiV1InventorySkuProductionEventWithBody(ctx context.Context, sku string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiV1InventorySkuProductionEvent(ctx context.Context, sku string, body PutApiV1InventorySkuProductionEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Reservation request
	GetApiV1Reservation(ctx context.Context, params *GetApiV1ReservationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ReservationWithBody request with any body
	PostApiV1ReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Reservation(ctx context.Context, body PostApiV1ReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ReservationID request
	GetApiV1ReservationID(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1UserWithBody request with any body
	PostApiV1UserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1User(ctx context.Context, body PostApiV1UserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAuthToken request
	PostAuthToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiV1AdminEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1AdminEnvRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Inventory(ctx context.Context, params *GetApiV1InventoryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1InventoryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1InventoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1InventoryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1Inventory(ctx context.Context, body PutApiV1InventoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1InventoryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1InventorySku(ctx context.Context, sku string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1InventorySkuRequest(c.Server, sku)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1InventorySkuProductionEventWithBody(ctx context.Context, sku string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1InventorySkuProductionEventRequestWithBody(c.Server, sku, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1InventorySkuProductionEvent(ctx context.Context, sku string, body PutApiV1InventorySkuProductionEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1InventorySkuProductionEventRequest(c.Server, sku, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Reservation(ctx context.Context, params *GetApiV1ReservationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ReservationRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1ReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ReservationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Reservation(ctx context.Context, body PostApiV1ReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ReservationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ReservationID(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ReservationIDRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1UserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1UserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1User(ctx context.Context, body PostApiV1UserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1UserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthTokenRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiV1AdminEnvRequest generates requests for GetApiV1AdminEnv
func NewGetApiV1AdminEnvRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/env")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1InventoryRequest generates requests for GetApiV1Inventory
func NewGetApiV1InventoryRequest(server string, params *GetApiV1InventoryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/inventory")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiV1InventoryRequest calls the generic PutApiV1Inventory builder with application/json body
func NewPutApiV1InventoryRequest(server string, body PutApiV1InventoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1InventoryRequestWithBody(server, "application/json", bodyReader)
}

// NewPutApiV1InventoryRequestWithBody generates requests for PutApiV1Inventory with any type of body
func NewPutApiV1InventoryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/inventory")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1InventorySkuRequest generates requests for GetApiV1InventorySku
func NewGetApiV1InventorySkuRequest(server string, sku string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sku", sku, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/inventory/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiV1InventorySkuProductionEventRequest calls the generic PutApiV1InventorySkuProductionEvent builder with application/json body
func NewPutApiV1InventorySkuProductionEventRequest(server string, sku string, body PutApiV1InventorySkuProductionEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1InventorySkuProductionEventRequestWithBody(server, sku, "application/json", bodyReader)
}

// NewPutApiV1InventorySkuProductionEventRequestWithBody generates requests for PutApiV1InventorySkuProductionEvent with any type of body
func NewPutApiV1InventorySkuProductionEventRequestWithBody(server string, sku string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sku", sku, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/inventory/%s/productionEvent", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ReservationRequest generates requests for GetApiV1Reservation
func NewGetApiV1ReservationRequest(server string, params *GetApiV1ReservationParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/reservation")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Sku != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sku", *params.Sku, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1ReservationRequest calls the generic PostApiV1Reservation builder with application/json body
func NewPostApiV1ReservationRequest(server string, body PostApiV1ReservationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ReservationRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1ReservationRequestWithBody generates requests for PostApiV1Reservation with any type of body
func NewPostApiV1ReservationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/reservation")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ReservationIDRequest generates requests for GetApiV1ReservationID
func NewGetApiV1ReservationIDRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "ID", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/reservation/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1UserRequest calls the generic PostApiV1User builder with application/json body
func NewPostApiV1UserRequest(server string, body PostApiV1UserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1UserRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1UserRequestWithBody generates requests for PostApiV1User with any type of body
func NewPostApiV1UserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAuthTokenRequest generates requests for PostAuthToken
func NewPostAuthTokenRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiV1AdminEnvWithResponse request
	GetApiV1AdminEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1AdminEnvResponse, error)

	// GetApiV1InventoryWithResponse request
	GetApiV1InventoryWithResponse(ctx context.Context, params *GetApiV1InventoryParams, reqEditors ...RequestEditorFn) (*GetApiV1InventoryResponse, error)

	// PutApiV1InventoryWithBodyWithResponse request with any body
	PutApiV1InventoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1InventoryResponse, error)

	PutApiV1InventoryWithResponse(ctx context.Context, body PutApiV1InventoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1InventoryResponse, error)

	// GetApiV1InventorySkuWithResponse request
	GetApiV1InventorySkuWithResponse(ctx context.Context, sku string, reqEditors ...RequestEditorFn) (*GetApiV1InventorySkuResponse, error)

	// PutApiV1InventorySkuProductionEventWithBodyWithResponse request with any body
	PutApiV1InventorySkuProductionEventWithBodyWithResponse(ctx context.Context, sku string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1InventorySkuProductionEventResponse, error)

	PutApiV1InventorySkuProductionEventWithResponse(ctx context.Context, sku string, body PutApiV1InventorySkuProductionEventJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1InventorySkuProductionEventResponse, error)

	// GetApiV1ReservationWithResponse request
	GetApiV1ReservationWithResponse(ctx context.Context, params *GetApiV1ReservationParams, reqEditors ...RequestEditorFn) (*GetApiV1ReservationResponse, error)

	// PostApiV1ReservationWithBodyWithResponse request with any body
	PostApiV1ReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ReservationResponse, error)

	PostApiV1ReservationWithResponse(ctx context.Context, body PostApiV1ReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ReservationResponse, error)

	// GetApiV1ReservationIDWithResponse request
	GetApiV1ReservationIDWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetApiV1ReservationIDResponse, error)

	// PostApiV1UserWithBodyWithResponse request with any body
	PostApiV1UserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1UserResponse, error)

	PostApiV1UserWithResponse(ctx context.Context, body PostApiV1UserJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1UserResponse, error)

	// PostAuthTokenWithResponse request
	PostAuthTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostAuthTokenResponse, error)
}

type GetApiV1AdminEnvResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiEnvResponse
	JSON401      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r GetApiV1AdminEnvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1AdminEnvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1AdminEnvResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1InventoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ApiProductResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r GetApiV1InventoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1InventoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1InventoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutApiV1InventoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ApiProductResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r PutApiV1InventoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1InventoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutApiV1InventoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1InventorySkuResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiProductResponse
	JSON401      *ApiProblem
	JSON404      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r GetApiV1InventorySkuResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1InventorySkuResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1InventorySkuResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutApiV1InventorySkuProductionEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ApiProductionEventResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON404      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r PutApiV1InventorySkuProductionEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1InventorySkuProductionEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutApiV1InventorySkuProductionEventResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1ReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ApiReservationResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON404      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r GetApiV1ReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1ReservationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1ReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ApiReservationResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON404      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r PostApiV1ReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1ReservationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1ReservationIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiReservationResponse
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON404      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r GetApiV1ReservationIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ReservationIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1ReservationIDResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1UserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON400      *ApiProblem
	JSON401      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r PostApiV1UserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1UserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1UserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAuthTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiTokenResponse
	JSON401      *ApiProblem
	JSON500      *ApiProblem
}

// Status returns HTTPResponse.Status
func (r PostAuthTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAuthTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAuthTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiV1AdminEnvWithResponse request returning *GetApiV1AdminEnvResponse
func (c *ClientWithResponses) GetApiV1AdminEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1AdminEnvResponse, error) {
	rsp, err := c.GetApiV1AdminEnv(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1AdminEnvResponse(rsp)
}

// GetApiV1InventoryWithResponse request returning *GetApiV1InventoryResponse
func (c *ClientWithResponses) GetApiV1InventoryWithResponse(ctx context.Context, params *GetApiV1InventoryParams, reqEditors ...RequestEditorFn) (*GetApiV1InventoryResponse, error) {
	rsp, err := c.GetApiV1Inventory(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1InventoryResponse(rsp)
}

// PutApiV1InventoryWithBodyWithResponse request with arbitrary body returning *PutApiV1InventoryResponse
func (c *ClientWithResponses) PutApiV1InventoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1InventoryResponse, error) {
	rsp, err := c.PutApiV1InventoryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1InventoryResponse(rsp)
}

func (c *ClientWithResponses) PutApiV1InventoryWithResponse(ctx context.Context, body PutApiV1InventoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1InventoryResponse, error) {
	rsp, err := c.PutApiV1Inventory(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1InventoryResponse(rsp)
}

// GetApiV1InventorySkuWithResponse request returning *GetApiV1InventorySkuResponse
func (c *ClientWithResponses) GetApiV1InventorySkuWithResponse(ctx context.Context, sku string, reqEditors ...RequestEditorFn) (*GetApiV1InventorySkuResponse, error) {
	rsp, err := c.GetApiV1InventorySku(ctx, sku, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1InventorySkuResponse(rsp)
}

// PutApiV1InventorySkuProductionEventWithBodyWithResponse request with arbitrary body returning *PutApiV1InventorySkuProductionEventResponse
func (c *ClientWithResponses) PutApiV1InventorySkuProductionEventWithBodyWithResponse(ctx context.Context, sku string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1InventorySkuProductionEventResponse, error) {
	rsp, err := c.PutApiV1InventorySkuProductionEventWithBody(ctx, sku, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1InventorySkuProductionEventResponse(rsp)
}

func (c *ClientWithResponses) PutApiV1InventorySkuProductionEventWithResponse(ctx context.Context, sku string, body PutApiV1InventorySkuProductionEventJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1InventorySkuProductionEventResponse, error) {
	rsp, err := c.PutApiV1InventorySkuProductionEvent(ctx, sku, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1InventorySkuProductionEventResponse(rsp)
}

// GetApiV1ReservationWithResponse request returning *GetApiV1ReservationResponse
func (c *ClientWithResponses) GetApiV1ReservationWithResponse(ctx context.Context, params *GetApiV1ReservationParams, reqEditors ...RequestEditorFn) (*GetApiV1ReservationResponse, error) {
	rsp, err := c.GetApiV1Reservation(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ReservationResponse(rsp)
}

// PostApiV1ReservationWithBodyWithResponse request with arbitrary body returning *PostApiV1ReservationResponse
func (c *ClientWithResponses) PostApiV1ReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ReservationResponse, error) {
	rsp, err := c.PostApiV1ReservationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ReservationResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1ReservationWithResponse(ctx context.Context, body PostApiV1ReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ReservationResponse, error) {
	rsp, err := c.PostApiV1Reservation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ReservationResponse(rsp)
}

// GetApiV1ReservationIDWithResponse request returning *GetApiV1ReservationIDResponse
func (c *ClientWithResponses) GetApiV1ReservationIDWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetApiV1ReservationIDResponse, error) {
	rsp, err := c.GetApiV1ReservationID(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ReservationIDResponse(rsp)
}

// PostApiV1UserWithBodyWithResponse request with arbitrary body returning *PostApiV1UserResponse
func (c *ClientWithResponses) PostApiV1UserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1UserResponse, error) {
	rsp, err := c.PostApiV1UserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1UserResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1UserWithResponse(ctx context.Context, body PostApiV1UserJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1UserResponse, error) {
	rsp, err := c.PostApiV1User(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1UserResponse(rsp)
}

// PostAuthTokenWithResponse request returning *PostAuthTokenResponse
func (c *ClientWithResponses) PostAuthTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostAuthTokenResponse, error) {
	rsp, err := c.PostAuthToken(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthTokenResponse(rsp)
}

// ParseGetApiV1AdminEnvResponse parses an HTTP response from a GetApiV1AdminEnvWithResponse call
func ParseGetApiV1AdminEnvResponse(rsp *http.Response) (*GetApiV1AdminEnvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1AdminEnvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetApiV1InventoryResponse parses an HTTP response from a GetApiV1InventoryWithResponse call
func ParseGetApiV1InventoryResponse(rsp *http.Response) (*GetApiV1InventoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1InventoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ApiProductResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiV1InventoryResponse parses an HTTP response from a PutApiV1InventoryWithResponse call
func ParsePutApiV1InventoryResponse(rsp *http.Response) (*PutApiV1InventoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1InventoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ApiProductResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1InventorySkuResponse parses an HTTP response from a GetApiV1InventorySkuWithResponse call
func ParseGetApiV1InventorySkuResponse(rsp *http.Response) (*GetApiV1InventorySkuResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1InventorySkuResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiProductResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiV1InventorySkuProductionEventResponse parses an HTTP response from a PutApiV1InventorySkuProductionEventWithResponse call
func ParsePutApiV1InventorySkuProductionEventResponse(rsp *http.Response) (*PutApiV1InventorySkuProductionEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1InventorySkuProductionEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ApiProductionEventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ReservationResponse parses an HTTP response from a GetApiV1ReservationWithResponse call
func ParseGetApiV1ReservationResponse(rsp *http.Response) (*GetApiV1ReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ApiReservationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1ReservationResponse parses an HTTP response from a PostApiV1ReservationWithResponse call
func ParsePostApiV1ReservationResponse(rsp *http.Response) (*PostApiV1ReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ApiReservationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ReservationIDResponse parses an HTTP response from a GetApiV1ReservationIDWithResponse call
func ParseGetApiV1ReservationIDResponse(rsp *http.Response) (*GetApiV1ReservationIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ReservationIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiReservationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1UserResponse parses an HTTP response from a PostApiV1UserWithResponse call
func ParsePostApiV1UserResponse(rsp *http.Response) (*PostApiV1UserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1UserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAuthTokenResponse parses an HTTP response from a PostAuthTokenWithResponse call
func ParsePostAuthTokenResponse(rsp *http.Response) (*PostAuthTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAuthTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
